//! OpenGit SSH Gateway - Identity-mapped SSH access for Git
//!
//! P4: SSH transport support via system sshd integration.
//!
//! Instead of implementing a custom SSH server, OpenGit SSH provides
//! system sshd configuration with identity-mapped authorized_keys:
//!
//! 1. `opengit-sshd setup` - Generates sshd_config + authorized_keys
//! 2. `opengit-sshd authorized-keys` - Print authorized_keys content
//! 3. `opengit-sshd config` - Print sshd_config content

use anyhow::Result;
use clap::{Parser, Subcommand};
use opengit_core::identity::IdentityStore;
use std::path::PathBuf;

#[derive(Parser, Debug)]
#[command(
    name = "opengit-sshd",
    version,
    about = "OpenGit SSH Gateway - Identity-mapped SSH for Git"
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Generate sshd_config and authorized_keys
    Setup {
        #[arg(short, long, default_value = "config/ssh")]
        output: PathBuf,
        #[arg(long, default_value = "config/identities.yaml")]
        identities: PathBuf,
        #[arg(short, long, default_value = "2222")]
        port: u16,
        #[arg(long, default_value = "./repos")]
        repos: PathBuf,
    },
    /// Print authorized_keys content
    AuthorizedKeys {
        #[arg(long, default_value = "config/identities.yaml")]
        identities: PathBuf,
    },
    /// Print sshd_config content
    Config {
        #[arg(short, long, default_value = "2222")]
        port: u16,
        #[arg(long, default_value = "./repos")]
        repos: PathBuf,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Setup {
            output,
            identities,
            port,
            repos,
        } => {
            let store = if identities.exists() {
                IdentityStore::from_file(&identities)?
            } else {
                IdentityStore::new()
            };

            std::fs::create_dir_all(&output)?;

            let authorized_keys = generate_authorized_keys(&store);
            let ak_path = output.join("authorized_keys");
            std::fs::write(&ak_path, &authorized_keys)?;
            println!("Generated: {}", ak_path.display());

            let sshd_config = generate_sshd_config(port, &repos, &ak_path);
            let config_path = output.join("sshd_config");
            std::fs::write(&config_path, &sshd_config)?;
            println!("Generated: {}", config_path.display());

            println!();
            println!("To start SSH server:");
            println!("  /usr/sbin/sshd -f {}", config_path.display());
        }
        Commands::AuthorizedKeys { identities } => {
            let store = if identities.exists() {
                IdentityStore::from_file(&identities)?
            } else {
                IdentityStore::new()
            };
            print!("{}", generate_authorized_keys(&store));
        }
        Commands::Config { port, repos } => {
            let ak_path = PathBuf::from("config/ssh/authorized_keys");
            print!("{}", generate_sshd_config(port, &repos, &ak_path));
        }
    }

    Ok(())
}

fn generate_authorized_keys(store: &IdentityStore) -> String {
    let mut output = String::new();
    output.push_str("# OpenGit Authorized Keys\n");
    output.push_str("# Auto-generated from identities.yaml\n\n");

    for identity in store.list() {
        if identity.ssh_keys.is_empty() {
            continue;
        }

        output.push_str(&format!(
            "# Identity: {} ({:?})\n",
            identity.name, identity.kind
        ));

        for key in &identity.ssh_keys {
            output.push_str(&format!(
                "command=\"OPENGIT_IDENTITY={name} git-shell -c \\\"$SSH_ORIGINAL_COMMAND\\\"\",no-port-forwarding,no-X11-forwarding,no-agent-forwarding {key}\n",
                name = identity.name,
                key = key
            ));
        }
        output.push('\n');
    }

    output
}

fn generate_sshd_config(
    port: u16,
    repos: &std::path::Path,
    authorized_keys: &std::path::Path,
) -> String {
    let _ = repos; // reserved for future repo-specific config
    format!(
        "# OpenGit SSH Server Configuration\n\
         # Auto-generated by opengit-sshd\n\n\
         Port {port}\n\
         ListenAddress 0.0.0.0\n\
         HostKey config/ssh/ssh_host_ed25519_key\n\n\
         PubkeyAuthentication yes\n\
         PasswordAuthentication no\n\
         AuthorizedKeysFile {authorized_keys}\n\n\
         AllowTcpForwarding no\n\
         X11Forwarding no\n\
         PermitTunnel no\n\
         PrintMotd no\n\n\
         ClientAliveInterval 300\n\
         ClientAliveCountMax 2\n\n\
         ForceCommand git-shell -c \"$SSH_ORIGINAL_COMMAND\"\n\n\
         Subsystem git /usr/bin/git-upload-pack\n",
        port = port,
        authorized_keys = authorized_keys.display(),
    )
}
